alloy:
  configMap:
    content: |
      discovery.kubernetes "nodes" {
        role = "node"
      }

      discovery.relabel "cadvisor" {
        targets    = discovery.kubernetes.nodes.targets
        rule {
          action = "labelmap"
          regex = "__meta_kubernetes_node_label_(.+)"
        }
        rule {
          action = "replace"
          target_label = "__address__"
          replacement = "kubernetes.default.svc:443"
        }
        rule {
          action = "replace"
          source_labels = ["__meta_kubernetes_node_name"]
          regex = "(.+)"
          target_label = "__metrics_path__"
          replacement = "/api/v1/nodes/${1}/proxy/metrics/cadvisor"
        }
      }

      prometheus.scrape "cadvisor" {
        job_name   = "integrations/kubernetes/cadvisor"
        targets    = discovery.relabel.cadvisor.output
        scheme     = "https"
        scrape_interval = "60s"
        bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        tls_config {
          insecure_skip_verify = true
        }

        forward_to = [prometheus.remote_write.default.receiver]
      }

      prometheus.remote_write "default" {
        endpoint {
            name = "hosted-prometheus"
            url  = "https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push"
        
            basic_auth {
              username = "xxxxxx"
              password = "xxxxxx"
            }
        }
      }
